version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./backend/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend1: &backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment: &backend-env
      SERVER_ID: "Backend 1"
      SIMULATE_LOAD: "true"
      RACK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskmanager
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/app:cached
      - /app/vendor
      - bundle_data:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        while ! nc -z db 5432; do
          sleep 1
        done &&
        echo 'PostgreSQL is ready!' &&
        bundle exec puma -p 4567 -b tcp://0.0.0.0"

  backend2:
    <<: *backend
    environment:
      <<: *backend-env
      SERVER_ID: "Backend 2"
      SIMULATE_LOAD: "false"

  backend3:
    <<: *backend
    environment:
      <<: *backend-env
      SERVER_ID: "Backend 3"
      SIMULATE_LOAD: "false"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:80
    depends_on:
      - nginx

volumes:
  pgdata:
  bundle_data:
